### ISSUE TITLE
Will you add support for iPad Pro 2022 with Kfd. maybe bcz offset. thanks

### ISSUE THREAD

**Issue by xcbjky** [c22dev/TipsGotTrolled#3]

**Comment by c22dev** [comment]
Hi !
If you're under 16.2 (not included), then yes, this app works for apple silicon (M1 and M2).
However, if you're under this version, the app, for now, doesn't support KFD. It should be included in the next major version.
Furthermore, your device is an Apple Silicon device and sadly, no developers have been able to find any of those offsets yet. 
This is still being looked at, and once offsets are available for your device you might, as well, get access to TrollStore.
I hope this answers your question.
