### ISSUE TITLE
Is KFD support still in the roadmap?

### ISSUE THREAD

**Issue by STMRabbit** [c22dev/TipsGotTrolled#5]
Hello, sorry for the verbose. I don't mean to push you or something, just curious if KFD support is still in plan? I need to know that to keep my sanity from sad life, and have something fun to expect.
I've heard a part of implementation of KFD is close source under Misaka's developer, is it true?   
Thank you very much and have a nice day!

**Comment by c22dev** [comment]
Closing issues on my GitHub rn
No haha, this project is more than dead imo
Please use [TrollInstallerX](https://github.com/alfiecg24/TrollInstallerX) instead
